CREATE TABLE IF NOT EXISTS calendar
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    day   SMALLINT NOT NULL
        CONSTRAINT bank_holiday_day_check CHECK ((day >= 1) AND (day <= 31)),
    month SMALLINT NOT NULL
        CONSTRAINT bank_holiday_month_check CHECK ((month >= 1) AND (month <= 12)),
    year  SMALLINT NOT NULL
);

CREATE TABLE weather
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    city        VARCHAR(255),
    temperature DOUBLE PRECISION,
    pressure    INTEGER,
    humidity    INTEGER,
    timestamp   TIMESTAMP
);

CREATE TABLE activity
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255),
    description TEXT,
    calendar_id BIGINT NOT NULL,
    FOREIGN KEY (calendar_id) REFERENCES calendar (id)
);





