server:
  shutdown: immediate

spring:
  liquibase:
    change-log: classpath:/database/changeLog.yaml
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?stringtype=unspecified&reWriteBatchedInserts=true&cachePrepStmts=true&useServerPrepStmts=true
    username: admin
    password: admin
    hikari:
      minimumIdle: 2
      maximumPoolSize: 20
      idleTimeout: 120000